# Generated by Django 5.2.10 on 2026-02-02 15:25

from django.db import migrations, models

import metrics.validators


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metricrecord",
            name="timestamp",
            field=models.BigIntegerField(
                validators=[metrics.validators.validate_unix_timestamp],
                verbose_name="Временая метка",
            ),
        ),
    ]
